version: '2'
services:
  mtpolicyd:
    build:
      context: .
    ports:
      - "12345:12345"
    volumes:
      - ".:/mtpolicyd"
    links:
      - memcached
      - openldap
      - mariadb

  memcached:
    image: memcached

  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Company"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
    volumes:
      - "ldap_config:/etc/ldap/slapd.d"
      - "ldap_data:/var/lib/ldap"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mtpolicyd
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mtpolicyd
    volumes:
      - "mariadb_data:/var/lib/mysql"

volumes:
  ldap_config:
  ldap_data:
  mariadb_data:

