#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ "$1" = configure ]; then
	lastversion="$2";
	
	getent group mtpolicyd >/dev/null 2>&1 || addgroup --system mtpolicyd
	getent passwd mtpolicyd >/dev/null 2>&1 ||
	adduser --system --home /var/run/mtpolicyd --no-create-home \
                --disabled-password --ingroup mtpolicyd mtpolicyd
fi

test -d /var/lib/mtpolicyd && \
  chown mtpolicyd:mtpolicyd /var/lib/mtpolicyd
if [ ! -e /var/lib/mtpolicyd/mtpolicyd.sqlite ] ; then
  touch /var/lib/mtpolicyd/mtpolicyd.sqlite
  chown mtpolicyd:mtpolicyd /var/lib/mtpolicyd/mtpolicyd.sqlite
  chmod 640 /var/lib/mtpolicyd/mtpolicyd.sqlite
fi
test -d /var/run/mtpolicyd && \
  chown mtpolicyd:mtpolicyd /var/run/mtpolicyd

#DEBHELPER#

exit 0
