# PODNAME: Mail::Mtpolicyd::Cookbook::ExtendedModule
# ABSTRACT: how to archieve certain tasks within a plugin

=head1 Extending your mtpolicyd plugin

How to archieve common task within your plugin.

=head2 Logging

You can output log messages to the mail.log from within your plugin by calling:

  $self->log( $r, '<log message>' );

The log() method is inherited from the Plugin base class.

The default log_level used is 4.

To debug your plugin you can overwrite the log_level in your plugins configuration:

  <Plugin hello-world>
    module = "HelloWorld"
    log_level = 2
  </Plugin>

This will cause your plugin to log with an higher log_level of 2.

=head2 Caching lookup results

If your plugin is called from the smtpd_recipient_restrictions if will be called once for every recipient. If your plugin does an lookup (dns, database, ...) should cache the result.

The L<Mail::MtPolicyd::Request> object implements the method do_cached() to archieve this:

  my ( $ip_result, $info ) = $r->do_cached('rbl-'.$self->name.'-result',
    sub { $self->_rbl->check( $ip ) } );

The first parameter is the key in the session to store the cached result. The second parameter is a function reference.

It will check if theres already an result stored in the given key within the session. In this case it will return the cached result as an array. If there is no result it will execute the code reference, store the result within the session and will also return an array containing the return values of the result.

=head2 Doing things only once per mail

If your plugin is called from the smtpd_recipient_restrictions if will be called once for every recipient but some tasks should only be performed once per mail.

The L<Mail::MtPolicyd::Request> object implements the method is_already_done() to archieve this:

  if( defined $self->score && ! $r->is_already_done( $self->name.'-score' ) ) {
    $self->add_score($r, $self->name => $self->score);
  }

The method takes the key in the session in which the flag is stored.

The example above will add a new score to the scoring, but only once per mail since the session is persisted across different checks.

=head2 Use scoring


